### PR TITLE
gradio web demo

### PR DESCRIPTION
**Pull request by AK391**
added web demo to use mobilestylegan in gradio

### CODE REVIEW

**Comment by bes-dev** [comment]
@AK391 thanks for your contribution! 
There are some points:
- Please, rename your demo like web_demo.py or something like this, and move your demo at the random_face/ folder. In this way we will can run your demo like 'python -m random_face.web_demo'
- Please, rename the block about your demo like "Web demo" and move it down after block "Demo" in the Readme file. Also, add instruction how to run this demo localy from command line.

**Comment by bes-dev** [comment]
@AK391 also, please determine valid range for alpha as [0; 1]

**Comment by AK391** [comment]
@bes-dev I have made the updates thanks

**Comment by AK391** [comment]
@bes-dev  this is meant to run in the web, to run locally you would do pip install gradio and run the web_demo.py file

**Comment by bes-dev** [comment]
Cool :+1:

**Pull request merged**
